[package]
name = "file-clean-rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.4.3", features = ["derive"] }
dirs-next = "2.0.0"
serde = { version = "1.0.189", features = ["derive"] }
serde_yaml = "0.9.25"
walkdir = "2.4.0"
