[package]
name = "file-clean-rust"
version = "0.1.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.4.8", features = ["cargo", "derive", "string"] }
colored = "2.0.4"
dirs-next = "2.0.0"
fancy-regex = "0.11.0"
itertools = "0.11.0"
md-5 = { version = "0.10.6", features = ["md5-asm"] }
quick-error = "2.0.1"
serde = { version = "1.0.189", features = ["derive"] }
serde_yaml = "0.9.25"
slab_tree = "0.3.2"
walkdir = "2.4.0"

[profile.release]
lto = true
opt-level = "s"
strip = true
